-- bootstrap lazy.nvim, LazyVim and your plugins
require("config.lazy")
require("config.colorscheme")
require("config.editor")
require("config.fugitive")
require("config.gitsigns")
require("config.keymaps")
require("config.lsp")
require("config.markdown-preview")
require("plugins.mojo")
require("config.notify")
require("config.neoscroll")
require("config.nvim-nu")
-- require("config.pylyzer")
require("config.rust-tools")
require("config.telescope")
require("config.toggleterm")
require("config.treesitter")
require("config.treesitter-context")
require("config.transparent")
