-- bootstrap lazy.nvim, LazyVim and your plugins
require("config.lazy")
require("config.colorscheme")
require("config.keymaps")
require("config.lsp")
require("config.notify")
require("config.nvim-nu")
require("config.rust-tools")
require("config.telescope")
require("config.toggleterm")
require("config.treesitter")
require("config.transparent")
require("config.markdown-preview")
